### ISSUE TITLE
Camera Position

### ISSUE THREAD

**Issue by wenyihan4396** [aim-uofa/AdelaiDepth#50]
Thank you for your amazing work!

Could you please tell me how to get the original camera position? I want to use original view port to observe the reconstructed model.

**Comment by wenyihan4396** [comment]
您好  我想用2d照片的原视角观察重建好的三维模型，请问怎么得到相机的观察位置呢

**Comment by guangkaixu** [comment]
Hello @wenyihan4396 , sorry for the late response. 

I don't know how to get the original camera, but I guess the transformation matrix should be a 4x4 identity matrix because there does not exist any transformation operation during reconstruction. By the way, I'm curious about why you want to observe the point cloud from the origin view of the image. You can only observe the original RGB image without any geometry information.

**Comment by wenyihan4396** [comment]
Thank you for your amazing model!
